# ansible role that installs the Apache2 web server
---
# Print out a message to the user about the playbook that's running
- name: Print message
  ansible.builtin.debug:
    msg: Running apache role main.yml playbook
# Install apt
- name: Install aptitude
  apt:
    name: aptitude
    state: latest
    update_cache: true
# Run apt update && apt upgrade
- name: sudo apt update && sudo apt upgrade 
  apt:
    upgrade: yes
    update_cache: yes
    cache_valid_time: 86400 #one day
# Install apache2 with apt  
- name: Install Apache2 with apt
  apt:
    pkg: apache2
    state: latest
    update_cache: true
# UFW update
- name: UFW - Allow Apache to use port 80
  community.general.ufw:
    rule: allow
    name: Apache
# Check the Apache2 webpage loads successfully
- name: Check that the Apache2 page loads successfully
  ansible.builtin.uri:
    url: "http://{{server_ip}}"
    return_content: true
# Print out a message to the user that the playbook is complete
- name: Playbook Complete
  ansible.builtin.debug:
    msg: apache setup complete! Try to log into your server on port 80
