---
- hosts: all
  become: true
  vars_files:
    - vars/default.yml
  roles:
    - common
    #- nginx
    - apache
    - mysql
    - php
    - wordpress
    #- wordpress_multisite
    #- ssl
    #- pressbooks
