# ansible role that installs MySQL server
---
# Print out a message to the user about the playbook that's running
- name: Print message
  ansible.builtin.debug:
    msg: Running mysql role main.yml playbook
# Install apt
- name: Install aptitude
  apt:
    name: aptitude
    state: latest
    update_cache: true
# Run apt update && apt upgrade
- name: sudo apt update && sudo apt upgrade 
  apt:
    upgrade: yes
    update_cache: yes
    cache_valid_time: 86400 #one day
# Install mysql-server and mysql-client with apt  
- name: Install mysql-server with apt
  apt:
    pkg:
      - mysql-server
      #- mysql-client
    state: latest
    update_cache: true
- name: Start mysql service
  service:
    name: mysql.service
    state: started
- name: add line to mysql config file
  lineinfile:
    dest: /etc/mysql/mysql.conf.d/mysqld.cnf
    insertafter: '[mysqld]'
    line: "default_authentication_plugin=caching_sha2_password"
- name: secure mysql with mysql_secure_installation script
  become: yes
  expect:
    command: mysql_secure_installation
    responses:
      'Enter current password for root': ''
      'Set root password': 'n'
      'Remove anonymous users': 'y'
      'Disallow root login remotely': 'y'
      'Remove test database': 'y'
      'Reload privilege tables now': 'y'
    timeout: 1
  register: secure_mysql
  failed_when: "'... Failed!' in secure_mysql.stdout_lines"
- name: restart mysql service
  service:
    name: mysql.service
    state: restarted
- name: Install PyMySQL
  apt:
    name: python3-pymysql
    state: present
- name: Removes all anonymous user accounts from mysql
  community.mysql.mysql_user:
    name: ''
    host_all: true
    state: absent

# Print out a message to the user that the playbook is complete
- name: Playbook Complete
  ansible.builtin.debug:
    msg: MySQL setup complete!
