---
# Run apt update && apt upgrade
- name: sudo apt update
  apt:
    update_cache: yes
    cache_valid_time: 86400 #one day

# Install certbot with apt  
- name: Install certbot and python3-certbot-apache with apt
  apt:
    pkg:
      - certbot
      - python3-certbot-apache
    state: latest
    update_cache: true

- name: UFW - Allow "Apache Full"
  community.general.ufw:
    rule: allow
    name: Apache Full

# ufw delete allow 'Apache'
- name: UFW - Delete "Apache" profile
  community.general.ufw:
    rule: allow
    name: "Apache"
    delete: true

- name: Obtain/renew SSL certificates with Certbot for Apache
  ansible.builtin.command: "certbot --apache -d {{ domain_name }} -d www.{{ domain_name}} --noninteractive --agree-tos -m {{ email }}"
  become: true
  args:
    creates: /etc/letsencrypt/live/example.com/fullchain.pem # Prevents running if cert exists
  register: certbot_output

- name: Print command output if it exists
  ansible.builtin.debug:
    msg: "certbot command output: {{ certbot_output.stdout }}"
  when: certbot_output | length > 0

# systemctl status certbot.timer is running
- name: Ensure the certbot.timer system service is running
  service:
    name: certbot.timer
    state: started
