---
# Run apt update && apt upgrade
- name: sudo apt update
  apt:
    update_cache: yes
    cache_valid_time: 86400 #one day
# Install mysql-server and mysql-client with apt  
- name: Install certbot and python3-certbot-apache with apt
  apt:
    pkg:
      - certbot
      - python3-certbot-apache
    state: latest
    update_cache: true
# sudo nano /etc/apache2/sites-available/your_domain.conf
# in your_domain.conf
# ...
# ServerName your_domain
# ServerAlias www.your_domain
#...

- name: Test the apache2 config
  ansible.builtin.command: "apache2ctl configtest"

# reload the apache2 service
- name: Restart apache2 service
  service:
    name: apache2
    state: restarted
# ufw allow 'Apache Full'
- name: UFW - Allow Apache Full, so port 80 and port 443 are allowed
  community.general.ufw:
    rule: allow
    name: "Apache Full"
# ufw delete allow 'Apache'
- name: UFW - Delete "Apache" profile
  community.general.ufw:
    rule: allow
    name: "Apache"
    delete: true
# run certbot
# but only run if
# /etc/letsencrypt/live/your_domain/fullchain.pem
# /etc/letsencrypt/live/your_domain/privkey.pem
# don't exhist yet
  # Check if fullchain.pem files already exhist on the server
- name: Check if fullchain.pem and privkey.pem files already exhists on the server
  stat: path=/etc/letsencrypt/live/{{ domain_name }}/fullchain.pem
  register: fullchain_path
- name: Check if privkey.pem files exhists
  stat: path=/etc/letsencrypt/live/{{ domain_name }}/privkey.pem
  register: privkey_path
  # Run certbot to generate SSL cert
- name: Run certbot to generate SSL cert
  ansible.builtin.command: "certbot certonly --apache --noninteractive --standalone --agree-tos -d {{ domain_name }} -d www.{{ domain_name }} -m {{ email }}"
  when: not privkey_path.stat.exists and not fullchain_path.stat.exists
  register: certbot_stdout 

- name: print out the certbot output
  debug:
    var: certbot_stdout.stdout_lines
    when: certbot_stdout

# systemctl status certbot.timer is running
- name: Ensure the certbot.timer system service is running
  service:
    name: certbot.timer
    state: started
