# ansible role that installs php
---
# Print out a message to the user about the playbook that's running
- name: Print message
  ansible.builtin.debug:
    msg: Running php role main.yml playbook
# Install apt
- name: Install aptitude
  apt:
    name: aptitude
    state: latest
    update_cache: true
# Run apt update && apt upgrade
- name: sudo apt update && sudo apt upgrade 
  apt:
    upgrade: yes
    update_cache: yes
    cache_valid_time: 86400 #one day
# Install mysql-server and mysql-client with apt  
- name: Install php with apt
  apt:
    pkg:
      - php8.1
      - libapache2-mod-php8.1
      - php8.1-mysql
      - php-common
      - php8.1-cli
      - php8.1-common
      - php8.1-opcache
      - php8.1-readline
      - php8.1-mbstring
      - php8.1-xml
      - php8.1-gd
      - php8.1-curl
    state: latest
    update_cache: true
# - name: Start mysql service
#   service:
#     name: mysql.service
#     state: started
